### ISSUE TITLE
Error calling s2-init-facebook

### ISSUE THREAD

**Issue by lduk** [splix/grails-spring-security-facebook#73]
I'm using:
```
        compile ':spring-security-core:2.0-RC4'
        compile ":spring-security-ui:1.0-RC2"
        compile ":spring-security-facebook:0.15.4-CORE2"
```

and when calling init:

```
grails> s2-init-facebook --stacktrace
| Packaging Grails application.....
Creating app based on configuration:
| Error Error running script s2-init-facebook --stacktrace: java.lang.ClassNotFoundException: org.codehaus.groovy.grails.plugin.springsecurity.SpringSecurityUtils (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.ClassNotFoundException: org.codehaus.groovy.grails.plugin.springsecurity.SpringSecurityUtils
	at java_lang_ClassLoader$loadClass.call(Unknown Source)
	at S2InitFacebook.configure(S2InitFacebook:73)
	at S2InitFacebook.this$4$configure(S2InitFacebook)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at S2InitFacebook$_run_closure1.doCall(S2InitFacebook:37)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
	at gant.Gant.withBuildListeners(Gant.groovy:427)
	at gant.Gant.this$2$withBuildListeners(Gant.groovy)
	at gant.Gant$this$2$withBuildListeners$0.callCurrent(Unknown Source)
	at gant.Gant.dispatch(Gant.groovy:415)
	at gant.Gant.this$2$dispatch(Gant.groovy)
	at gant.Gant.invokeMethod(Gant.groovy)
	at gant.Gant.executeTargets(Gant.groovy:591)
	at gant.Gant.executeTargets(Gant.groovy:590)
	at org.grails.wrapper.GrailsWrapper.main(GrailsWrapper.java:93)
| Error Error running script s2-init-facebook --stacktrace: java.lang.ClassNotFoundException: org.codehaus.groovy.grails.plugin.springsecurity.SpringSecurityUtils
```

**Comment by splix** [comment]
fixed by [99f15d85aaff2354a44806cc4b3f07abd7b9bca9]
