### ISSUE TITLE
NullPointerException when updating auth token

### ISSUE THREAD

**Issue by calebcassel** [splix/grails-spring-security-facebook#79]
I keep seeing NPEs when the plugin attempts to update a user's auth token. I'm not sure if this is a problem with the plugin or a problem somewhere on my part.
```
java.lang.NullPointerException
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:2318)
	at com.the6hours.grails.springsecurity.facebook.FacebookAuthToken.toString(FacebookAuthToken.groovy:27)
	at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:616)
	at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:559)
	at org.codehaus.groovy.runtime.InvokerHelper.toString(InvokerHelper.java:126)
	at org.codehaus.groovy.runtime.InvokerHelper.write(InvokerHelper.java:511)
	at groovy.lang.GString.writeTo(GString.java:190)
	at groovy.lang.GString.toString(GString.java:162)
	at org.codehaus.groovy.reflection.stdclasses.StringCachedClass.coerceArgument(StringCachedClass.java:45)
	at org.codehaus.groovy.reflection.ParameterTypes.coerceArgumentsToClasses(ParameterTypes.java:143)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:208)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.the6hours.grails.springsecurity.facebook.DefaultFacebookAuthDao$_updateToken_closure9.doCall(DefaultFacebookAuthDao.groovy:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:88)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:85)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:814)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:714)
	at com.leyef.FacebookUser.withTransaction(FacebookUser.groovy)
	at com.leyef.FacebookUser$withTransaction.call(Unknown Source)
	at com.the6hours.grails.springsecurity.facebook.DefaultFacebookAuthDao.updateToken(DefaultFacebookAuthDao.groovy:271)
	at com.the6hours.grails.springsecurity.facebook.FacebookAuthProvider.authenticate(FacebookAuthProvider.groovy:85)
```

```
ERROR facebook.DefaultFacebookAuthDao  - Can't update token
java.lang.NullPointerException
	at com.the6hours.grails.springsecurity.facebook.FacebookAuthToken.toString(FacebookAuthToken.groovy:27)
	at com.the6hours.grails.springsecurity.facebook.DefaultFacebookAuthDao$_updateToken_closure9.doCall(DefaultFacebookAuthDao.groovy:292)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:814)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:714)
	at com.the6hours.grails.springsecurity.facebook.DefaultFacebookAuthDao.updateToken(DefaultFacebookAuthDao.groovy:271)
	at com.the6hours.grails.springsecurity.facebook.FacebookAuthProvider.authenticate(FacebookAuthProvider.groovy:85)
	at com.the6hours.grails.springsecurity.facebook.FacebookAuthRedirectFilter.attemptAuthentication(FacebookAuthRedirectFilter.groovy:58)
	at com.the6hours.grails.springsecurity.facebook.FacebookAuthRedirectFilter.doFilter(FacebookAuthRedirectFilter.groovy:46)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
```

**Comment by john-london** [comment]
Hi Caleb,

I was getting similar NPEs.  They appear to be due to the fact that the toString() method of FacebookAuthToken references authorities (authorities.collect, here: https://github.com/splix/grails-spring-security-facebook/blob/master/src/groovy/com/the6hours/grails/springsecurity/facebook/FacebookAuthToken.groovy#L27) when authorities is null because it's never set.  The existing constructor doesn't actually set authorities, even though it calls super() with an array.  You can see this exception in the console of the example project (http://github.com/splix/grails-facebook-authentication-example) if you log in to FB then log out (thereby creating an access token) and then logging in again.

I've created a pull request for Igor (@splix) which I believe fixes the problem.

Regards,

John

**Comment by splix** [comment]
Thanks guys, will merge and release a new version of the plugin this weekend

**Comment by calebcassel** [comment]
Awesome. Thanks for the amazingly fast turnaround on this!
