### ISSUE TITLE
FacebookAuthProvider Can't fetch access_token for code

### ISSUE THREAD

**Issue by moniman** [splix/grails-spring-security-facebook#81]
Hi, 

Sometimes I see that errors in my logs.
I can't understand why.
Have you an idea ?

grails 2.4.4
java 8 
spring-security-facebook:0.17
spring-security-core:2.0-RC4

2015-02-03 16:49:18 facebook.FacebookAuthProvider Can't fetch access_token for code 'AQBpEDsLyZyZyUSk-WvcSgwt_Dwks0tBGzMvS89D41YS0qkzSb9ypjPIp7hP1aETwN4hYwhXvcLVhcQEcfM0oxViSTLE5e2FuxtuJsR4CXz5Xa-EUkRIBaKK5XvM7Fil3nKLr06XLzODB7IWkjKtsFh9qCpjiKlqWYxqv8ZenkbRXdv50G7JZo_mY8xPK2Cg3vLEOHYiVytb7PgufKuJyJykEAWs5wcf7_pZmWiFh0fADFWBtALKXp79PrPcHD1p_dYFS1kuq0GgvM_G2TDn0FB_raIdJwNHkYqC4v3s__xfrWL1hQ1dy3sr2W7lK5aWBozVkaGxWIpAfziP9KVprqgm'
2015-02-03 16:49:18 errors.GrailsExceptionResolver NullPointerException occurred when processing request: [GET] /
Cannot get property 'metaClass' on null object. Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:applyLayout>: Error executing tag <g:render>: Cannot get property 'metaClass' on null object
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
	at com.the6hours.grails.springsecurity.facebook.FacebookAuthRedirectFilter.doFilter(FacebookAuthRedirectFilter.groovy:46)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:applyLayout>: Error executing tag <g:render>: Cannot get property 'metaClass' on null object
	at gsp_myapp_homeindex_gsp.run(gsp_myapp_homeindex_gsp.groovy:346)
	... 9 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Cannot get property 'metaClass' on null object
	at gsp_myapp_layoutsmain_gsp$_run_closure2.doCall(gsp_myapp_layoutsmain_gsp.groovy:69)
	at gsp_myapp_layoutsmain_gsp.run(gsp_myapp_layoutsmain_gsp.groovy:111)
	... 10 more
Caused by: java.lang.NullPointerException: Cannot get property 'metaClass' on null object
	at grails.plugin.springsecurity.SecurityTagLib.determineSource(SecurityTagLib.groovy:264)
	at grails.plugin.springsecurity.SecurityTagLib$_closure4.doCall(SecurityTagLib.groovy:105)
	at gsp_myapp_menu_navbar_gsp.run(gsp_myapp_menu_navbar_gsp.groovy:14)
	... 12 more
2015-02-03 16:49:24 facebook.FacebookAuthProvider Can't fetch access_token for code 'AQBpEDsLyZyZyUSk-WvcSgwt_Dwks0tBGzMvS89D41YS0qkzSb9ypjPIp7hP1aETwN4hYwhXvcLVhcQEcfM0oxViSTLE5e2FuxtuJsR4CXz5Xa-EUkRIBaKK5XvM7Fil3nKLr06XLzODB7IWkjKtsFh9qCpjiKlqWYxqv8ZenkbRXdv50G7JZo_mY8xPK2Cg3vLEOHYiVytb7PgufKuJyJykEAWs5wcf7_pZmWiFh0fADFWBtALKXp79PrPcHD1p_dYFS1kuq0GgvM_G2TDn0FB_raIdJwNHkYqC4v3s__xfrWL1hQ1dy3sr2W7lK5aWBozVkaGxWIpAfziP9KVprqgm'
2015-02-03 16:49:24 errors.GrailsExceptionResolver NullPointerException occurred when processing request: [GET] /
Cannot get property 'metaClass' on null object. Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:applyLayout>: Error executing tag <g:render>: Cannot get property 'metaClass' on null object
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
	at com.the6hours.grails.springsecurity.facebook.FacebookAuthRedirectFilter.doFilter(FacebookAuthRedirectFilter.groovy:46)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:applyLayout>: Error executing tag <g:render>: Cannot get property 'metaClass' on null object
	at gsp_myapp_homeindex_gsp.run(gsp_myapp_homeindex_gsp.groovy:346)
	... 9 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Cannot get property 'metaClass' on null object
	at gsp_myapp_layoutsmain_gsp$_run_closure2.doCall(gsp_myapp_layoutsmain_gsp.groovy:69)
	at gsp_myapp_layoutsmain_gsp.run(gsp_myapp_layoutsmain_gsp.groovy:111)
	... 10 more
Caused by: java.lang.NullPointerException: Cannot get property 'metaClass' on null object
	at grails.plugin.springsecurity.SecurityTagLib.determineSource(SecurityTagLib.groovy:264)
	at grails.plugin.springsecurity.SecurityTagLib$_closure4.doCall(SecurityTagLib.groovy:105)
	at gsp_myapp_menu_navbar_gsp.run(gsp_myapp_menu_navbar_gsp.groovy:14)
	... 12 more

**Comment by ptoner** [comment]
I get the same thing. It's semi-often.

**Comment by senty** [comment]
Same here.

When running app localy - development - it works 100% alright. But when i upload it into server :
- redirect me to FB for login
- than long loading
- at the end it is error on my page with : Can't fetch access_token for code

can someone help pls ?
